### PR TITLE
fix ./script/ -> ./scripts/ and add verbosity

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by pierreozoux** [comment]
You don't need to run the script as root. It should ask you. Just to modify /etc/hosts

**Comment by pierreozoux** [comment]
I close this as of:
https://github.com/pierreozoux/IndiePaaS/commit/632afe7ce051766d2e8530bb0bede557ebdbeac4
https://github.com/pierreozoux/IndiePaaS/commit/cc90d3b3715cbadfa994dde005804cfbd5a98fec

And please, do one commit per change. If not, it is difficult to read.

**Comment by michielbdejong** [comment]
Ah ok, I interpreted the "needs root access" comment as "you need to run this as root". You could make that clearer.

**Comment by pierreozoux** [comment]
Ok, done: https://github.com/pierreozoux/IndiePaaS/commit/a2ffe2d9a81fc79f18ec00a9d9ad2bf23bb15fb9

**Pull request closed without merging**
